---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-image-updater
  annotations:
    codefresh.io/app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        imagePullPolicy: Always
        image: quay.io/miniprojects/saysmooth:1.3.0
        ports:
        - containerPort: 5000
