apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: always-latest01
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: example=ruthvik2424/demoproject
    argocd-image-updater.argoproj.io/example.update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/ruthvik2424/cicd-pipeline.git
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/qa/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
